# Generated by Django 4.2.16 on 2026-06-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0003_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('sick', 'Sick Leave'), ('lwp', 'Leave Without Pay'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave')], max_length=20, unique=True)),
                ('annual_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('can_carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward_days', models.PositiveIntegerField(default=0)),
                ('policy_note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hrms_leave_policies',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('sick', 'Sick Leave'), ('lwp', 'Leave Without Pay'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave')], max_length=20)),
                ('duration', models.CharField(choices=[('full_day', 'Full Day'), ('half_morning', 'Half Day (Morning)'), ('half_afternoon', 'Half Day (Afternoon)')], default='full_day', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('l2_pending', 'L2 Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_lwp', models.BooleanField(default=False)),
                ('l1_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('l1_remarks', models.TextField(blank=True, default='')),
                ('l1_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('l2_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('l2_remarks', models.TextField(blank=True, default='')),
                ('l2_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('contact_during_leave', models.CharField(blank=True, default='', max_length=30)),
                ('handover_to', models.CharField(blank=True, default='', max_length=150)),
                ('handover_notes', models.TextField(blank=True, default='')),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('l1_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1_leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('l2_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l2_leave_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_leave_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('sick', 'Sick Leave'), ('lwp', 'Leave Without Pay'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_leave_balances',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
