# Generated by Django 4.2.16 on 2026-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_email_templates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["template_type", "display_name"]},
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="available_variables",
            field=models.JSONField(
                default=list,
                help_text="List of {VARIABLE} names supported by this template.",
            ),
        ),
    ]
