# Generated by Django 4.2.16 on 2026-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_smtpsettings_smtp_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="otp",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="is_used",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
