# Generated by Django 4.2.16 on 2026-06-25 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_department_designation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplateAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="email_template_attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField(help_text="File size in bytes")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="accounts.emailtemplate",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_template_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hrms_email_template_attachments",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
