# Generated by Django 4.2.16 on 2026-06-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_phone_date_of_joining_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='RSS', max_length=10)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_code_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_employee_code_settings',
            },
        ),
    ]
