# Generated by Django 4.2.16 on 2026-06-28 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_employee_code_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted — awaiting approval'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('year_of_passing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('previous_employer', models.CharField(blank=True, max_length=200)),
                ('previous_designation', models.CharField(blank=True, max_length=200)),
                ('leaving_reason', models.TextField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_branch_name', models.CharField(blank=True, max_length=200)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], max_length=10)),
                ('emergency_name', models.CharField(blank=True, max_length=150)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('aadhaar_card', 'Aadhaar Card'), ('degree_certificate', 'Degree Certificate'), ('experience_letter', 'Experience Letter'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_employee_documents',
                'ordering': ['document_type', '-uploaded_at'],
            },
        ),
    ]
