# Generated by Django 4.2.16 on 2026-06-29 10:33

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_onboarding_permission_and_portal_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocument",
            name="file",
            field=models.FileField(upload_to=apps.accounts.models._employee_doc_path),
        ),
    ]
