# Generated by Django 4.2.16 on 2026-06-29 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_company_portal_url_and_onboarding_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('leave', 'Leave Request'), ('expense', 'Expense Claim'), ('resignation', 'Resignation'), ('loan', 'Loan Request')], max_length=15, unique=True)),
                ('l1_approver_role', models.CharField(choices=[('reporting_manager', 'Reporting Manager'), ('hr_manager', 'HR Manager'), ('admin', 'Admin')], default='reporting_manager', max_length=20)),
                ('l2_approver_role', models.CharField(blank=True, choices=[('reporting_manager', 'Reporting Manager'), ('hr_manager', 'HR Manager'), ('admin', 'Admin')], default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rule_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_approval_workflow_rules',
            },
        ),
        migrations.CreateModel(
            name='EmployeeApprovalOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('leave', 'Leave Request'), ('expense', 'Expense Claim'), ('resignation', 'Resignation'), ('loan', 'Loan Request')], max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_overrides', to=settings.AUTH_USER_MODEL)),
                ('l1_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1_approval_overrides', to=settings.AUTH_USER_MODEL)),
                ('l2_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l2_approval_overrides', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_override_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_employee_approval_overrides',
                'unique_together': {('employee', 'workflow_type')},
            },
        ),
    ]
