# Generated by Django 4.2.16 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_role_designation_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("draft", "In Progress"),
                    ("submitted", "Submitted — awaiting approval"),
                    ("complete", "Complete"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
