# Generated by Django 4.2.16 on 2026-06-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0003_branch_permissions"),
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="branch.branch",
            ),
        ),
    ]
