# Generated by Django 4.2.16 on 2026-06-28 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0002_add_branch_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='portal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_portal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('screening', 'Screening'), ('interview_scheduled', 'Interview Scheduled'), ('interview_done', 'Interview Done'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('converted', 'Converted to Employee'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
